apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: policy-odf-noobaa
spec:
  remediationAction: enforce
  severity: medium
  object-templates:
    # Create NooBaa CR with manual default backing store management
    # This prevents operator from auto-creating aws-s3 or RGW backing stores
    - complianceType: musthave
      objectDefinition:
        apiVersion: noobaa.io/v1alpha1
        kind: NooBaa
        metadata:
          name: noobaa
          namespace: openshift-storage
        spec:
          manualDefaultBackingStore: true
          coreResources:
            limits:
              cpu: "2"
              memory: 8Gi
            requests:
              cpu: "1"
              memory: 4Gi
          dbResources:
            limits:
              cpu: "2"
              memory: 8Gi
            requests:
              cpu: "1"
              memory: 4Gi
          endpoints:
            minCount: 2
            maxCount: 2
            resources:
              limits:
                cpu: "2"
                memory: 4Gi
              requests:
                cpu: "1"
                memory: 2Gi
    # Create pvPool BackingStore for local Ceph storage
    - complianceType: musthave
      objectDefinition:
        apiVersion: noobaa.io/v1alpha1
        kind: BackingStore
        metadata:
          name: noobaa-pv-backing-store
          namespace: openshift-storage
        spec:
          type: pv-pool
          pvPool:
            numVolumes: 3
            resources:
              limits:
                cpu: "2"
                memory: 8Gi
              requests:
                cpu: "1"
                memory: 4Gi
                storage: 100Gi
            storageClass: ocs-storagecluster-ceph-rbd
    # Create default BucketClass using only pvPool BackingStore (single-tier)
    - complianceType: musthave
      objectDefinition:
        apiVersion: noobaa.io/v1alpha1
        kind: BucketClass
        metadata:
          name: noobaa-default-bucket-class
          namespace: openshift-storage
        spec:
          placementPolicy:
            tiers:
              - backingStores:
                  - noobaa-pv-backing-store
