apiVersion: v1
kind: ConfigMap
metadata:
  name: opp-settings
  namespace: policies
data:
  vmwareReplicas: "6"
  vmwareCPU: "8"
  vmwareMemory: "32768"
  awsReplicas: "2"
  awsInstanceType: m6a.2xlarge
