apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: observability-addon-install-strategy
spec:
  remediationAction: enforce
  severity: low
  object-templates:
    - complianceType: musthave
      objectDefinition:
        apiVersion: addon.open-cluster-management.io/v1alpha1
        kind: ClusterManagementAddOn
        metadata:
          name: observability-controller
        spec:
          # Configure automatic installation strategy (restore ACM 2.14 behavior)
          # ACM 2.14: default was Placements (auto-install on all clusters)
          # ACM 2.15+: default changed to Manual (requires explicit ManagedClusterAddOn creation)
          # This configuration restores the automatic installation behavior
          # Install to both hub cluster (local-cluster) and all managed clusters
          installStrategy:
            type: Placements
            placements:
              # Install to hub cluster (local-cluster)
              - name: placement-openshift-plus-hub
                namespace: policies
              # Install to all managed clusters
              - name: placement-openshift-plus-clusters
                namespace: policies
